ReadyFundPriories=[
('AUCA FUND priorities', 'AUCA FUND priorities'), ('Unrestricted Fund', 'Unrestricted Fund'), ('Scholarships', 'Scholarships'),
 ('New Generation Academy (NGA)', 'New Generation Academy (NGA)'), ('Fatima Khalil Human Rights Scholarship Drive', 'Fatima Khalil Human Rights Scholarship Drive'),
 ('Student Initiative Development Program (SIDP)', 'Student Initiative Development Program (SIDP)'), ('Library and Technology Development', 'Library and Technology Development'), 
 ('Student Travel Grants', 'Student Travel Grants'), ('Staff Development', 'Staff Development'), ('Faculty Development', 'Faculty Development'),
 ('Research Development', 'Research Development'),
 ('Civic Engagement', 'Civic Engagement'), ('Alumni Fund', 'Alumni Fund'), ('Other', 'Other')]

ReadyConnetions=[('Alumni', 'Alumni'), ('Trustee', 'Trustee'), ('Преподаватель / сотрудник', 'Преподаватель / сотрудник'), 
 ('Студент', 'Студент'), ('Parent / Grandparent', 'Parent / Grandparent'), ('Друг', 'Друг')]
countries_list = [    
    ('Киргизия', 'Киргизия'),
    ('Соединенные Штаты', 'Соединенные Штаты'),
    ('Австралия', 'Австралия'),
    ('Австрия', 'Австрия'),
    ('Азербайджан', 'Азербайджан'),
    ('Аландские о-ва', 'Аландские о-ва'),
    ('Албания', 'Албания'),
    ('Алжир', 'Алжир'),
    ('Американское Самоа', 'Американское Самоа'),
    ('Ангилья', 'Ангилья'),
    ('Ангола', 'Ангола'),
    ('Андорра', 'Андорра'),
    ('Антарктида', 'Антарктида'),
    ('Антигуа и Барбуда', 'Антигуа и Барбуда'),
    ('Аргентина', 'Аргентина'),
    ('Армения', 'Армения'),
    ('Аруба', 'Аруба'),
    ('Афганистан', 'Афганистан'),
    ('Багамы', 'Багамы'),
    ('Бангладеш', 'Бангладеш'),
    ('Барбадос', 'Барбадос'),
    ('Бахрейн', 'Бахрейн'),
    ('Беларусь', 'Беларусь'),
    ('Белиз', 'Белиз'),
    ('Бельгия', 'Бельгия'),
    ('Бенин', 'Бенин'),
    ('Бермуды', 'Бермуды'),
    ('Болгария', 'Болгария'),
    ('Боливия', 'Боливия'),
    ('Бонэйр, Синт-Эстатиус и Саба', 'Бонэйр, Синт-Эстатиус и Саба'),
    ('Босния и Герцеговина', 'Босния и Герцеговина'),
    ('Ботсвана', 'Ботсвана'),
    ('Бразилия', 'Бразилия'),
    ('Британская территория в Индийском океане', 'Британская территория в Индийском океане'),
    ('Бруней-Даруссалам', 'Бруней-Даруссалам'),    
]

