# Generated by Django 4.2.9 on 2024-02-04 09:47

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Kyrgyz_som', models.DecimalField(decimal_places=2, max_digits=10)),
                ('USD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('Confirm_Email', models.EmailField(max_length=254)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=40)),
                ('Connection', models.CharField(blank=True, choices=[('Alumni', 'Alumni'), ('Trustee', 'Trustee'), ('Преподаватель / сотрудник', 'Преподаватель / сотрудник'), ('Студент', 'Студент'), ('Parent / Grandparent', 'Parent / Grandparent'), ('Друг', 'Друг')], max_length=50, null=True)),
                ('Fund', models.CharField(blank=True, choices=[('AUCA FUND priorities', 'AUCA FUND priorities'), ('Unrestricted Fund', 'Unrestricted Fund'), ('Scholarships', 'Scholarships'), ('New Generation Academy (NGA)', 'New Generation Academy (NGA)'), ('Fatima Khalil Human Rights Scholarship Drive', 'Fatima Khalil Human Rights Scholarship Drive'), ('Student Initiative Development Program (SIDP)', 'Student Initiative Development Program (SIDP)'), ('Library and Technology Development', 'Library and Technology Development'), ('Student Travel Grants', 'Student Travel Grants'), ('Staff Development', 'Staff Development'), ('Faculty Development', 'Faculty Development'), ('Research Development', 'Research Development'), ('Civic Engagement', 'Civic Engagement'), ('Alumni Fund', 'Alumni Fund'), ('Other', 'Other')], max_length=60, null=True)),
                ('Country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('Inspired', models.TextField(blank=True, max_length=200, null=True)),
                ('Comment', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
